---
title: "Course Preparation"
subtitle: "Things required before getting an add code"

format:
  html:
    code-fold: true
    code-tools: FALSE
    code-copy: true
    highlight-style: github
---

This course is designed for graduate students with core computational competence and an appropriate data set for analyses to be performed during the course. Normally, before class starts (and add codes are distributed) the following tasks need to be completed.

1.  Submit your github ID using [this form](https://docs.google.com/forms/d/e/1FAIpQLSd0MUPej4xJhIWiS8wLztpzXK7iak3DYPjFLzIcgAKIMTfy2Q/viewform?usp=sf_link).

2.  [Establish account](https://robertslab.github.io/resources/mox_Adding-a-User/) on Roberts Lab (srlab) hyak account

3.  Read: [Introducing the Shell](https://swcarpentry.github.io/shell-novice/01-intro.html)\
    Read: [Navigating Files and Directories](https://swcarpentry.github.io/shell-novice/02-filedir.html)\
    Complete [this bash tutorial](https://sr320.github.io/course-fish546-2025/assignments/00-bash.html)

4.  Read: [Roberts Lab: Things you should know] (https://robertslab.github.io/tusk/)

5.  Learn (remember) proper project (repo) structure.

::: panel-tabset
## File Structure

-   Good file structure

    -   All project files in one main folder

    -   Subfolders (data, code, output)

-   Main folder is R project

    -   Self-contained project

    -   Use relative instead of absolute paths

-   Good folder & file names

    -   Descriptive but not too long

    -   No spaces

    -   Consistent format

## Data

-   Raw data

    -   In separate folder from cleaned data

    -   Never change!

    -   Each file should have metadata

## Code

-   Scripts with code

    -   Relative file paths to read in and create files

    -   Lots of comments

    -   Order: libraries, data, user-created functions, everything else

    -   Good variable & column names
:::
